[package]
name = "hex-utils"
version = "0.1.9"
authors = ["Anicka Burova <anicka.burova@gmail.com>"]
license = "MIT License"
description = "Xxd output from binary input with configurable formatting."

[dependencies]









